### ISSUE TITLE
Incorrect face's texturing

### ISSUE THREAD

**Issue by NagoyaKei** [AleksandrCherepanov/rr#2]
I made a simple 2 faces model with UV Map and you can see that face №2 (top-left) renders incorrectly
_model and UV Map_
![blender_IMnD3auSbQ](https://github.com/AleksandrCherepanov/rr/assets/8111586/b33c1c42-05d6-4b7a-8b23-47adb8370cc7)

_render result_
![image](https://github.com/AleksandrCherepanov/rr/assets/8111586/186a1e20-4209-49c8-9148-a05f9d6f9ae1)

_obj file_
[plane.zip](https://github.com/AleksandrCherepanov/rr/files/14978185/plane.zip)

**Comment by AleksandrCherepanov** [comment]
I've fixed this bug, you can check it now.

**Comment by NagoyaKei** [comment]
Everything is greate now, thx!
